name: uclgeog
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python
  - conda-build
  - nb_conda_kernels
  - libgdal
  - geopandas
  - rasterio
  - scipy
  - gdal
  - beautifulsoup4
  - fiona
  - numpy
  - statsmodels
  - cartopy
  - scikit-image
  - netcdf4
  - scikit-learn
  - matplotlib
  - pandas
  - shapely
  - ipyleaflet
  - pytest
  - seaborn
  - hdf5
  - sympy
  - iris
  - autopep8
  - flake8
  - ipython
  - ipywidgets
  - nbdime
  - xarray
  - jupyter_contrib_nbextensions
  - spyder
  - dask
  - black
  - folium
  - jupyter_highlight_selected_word
  - jupyter_contrib_core
  - jupyter_console
  - pandocfilters
  - nbconvert
  - jupyterlab
  - nb_conda
  - jupyter
  - nbformat
  - pandoc
  - nco
  - pyephem
  - libnetcdf
  - jupyter_nbextensions_configurator
  - git
  - jupyterlab_code_formatter
  - nbsphinx
  - sphinx
  - ipykernel
  - importlib_metadata
  - pip
  - pip:
    - jupyter_http_over_ws
