name: uclgeog
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - conda-build
  - libgdal
  - geopandas
  - rasterio
  - scipy
  - gdal
  - beautifulsoup4
  - fiona
  - numpy
  - statsmodels
  - cartopy
  - scikit-image
  - netcdf4
  - scikit-learn
  - matplotlib-base
  - pandas
  - shapely
  - ipyleaflet
  - pytest
  - seaborn
  - hdf5
  - iris
  - flake8
  - ipython
  - ipywidgets
  - nbdime
  - xarray
  - dask
  - black
  - folium
  - jupyter_console
  - pandocfilters
  - nbconvert
  - jupyterlab
  - jupyter
  - nbformat
  - pandoc
  - nco
  - pyephem
  - libnetcdf
  - sphinx
  - ipykernel
  - xeus-python
  - ipympl
  - pip
