name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"  
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"  
        image_name: geog 
        push_image_and_stages: true
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag geog:$(date +%s)
      

