name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"  
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"  
        image_name: geog
        push_git_tag: true
        push_image_and_stages: docker run geog:latest

# - name: Login to DockerHub Registry
#      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#    - name: Get the version
#      id: vars
#      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
#    - name: Build the tagged Docker image
#      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/geog:${{steps.vars.outputs.tag}}
#    - name: Push the tagged Docker image
#      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/geog:${{steps.vars.outputs.tag}}
#    - name: Build the latest Docker image
#      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/geog:latest
#    - name: Push the latest Docker image
#      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/geog:latest
      

